<script>

const SVC_FEVER = 'fever'
const SVC_URTI = 'urti'
const SVC_ASTHMA = 'asthma'
const SVC_TUBERCULOSIS = 'tuberculosis'
const SVC_ABD_DISCOMFORT = 'abd discomfort'
const SVC_AGE = 'age'
const SVC_DIABETES = 'diabetes'
const SVC_HYPERTENSION = 'hypertension'
const SVC_PSY = 'psy'
const SVC_KBM = 'kbm'
const SVC_METHADONE = 'methadone'
const SVC_BLOOD_TAKING = 'blood taking'
const SVC_WOUND_CARE = 'wound care'
const SVC_FUNDOSCOPY = 'fundoscopy'
const SVC_XRAY = 'x-ray'
const SVC_DIET_COUNSELLING = 'diet counselling'
const SVC_PREMARITAL_SCREENING = 'premarital screening'
const SVC_MEDICAL_CHECKUP = 'medical checkup'
const SVC_ANTENATAL_BOOKING = 'antenatal booking'
const SVC_ANTENATAL_FUP = 'antenatal followup'
const SVC_POSTNATAL = 'postnatal'
const SVC_FAMILY_PLANNING = 'family planning'
const SVC_PAP_SMEAR = 'pap smear'
const SVC_IMMUNIZATION = 'immunization'
const SVC_OTHER_PROBS = 'other problems'

const SVC_ALL = [
  SVC_FEVER,
  SVC_URTI,
  SVC_ASTHMA,
  SVC_TUBERCULOSIS,
  SVC_ABD_DISCOMFORT,
  SVC_AGE,
  SVC_DIABETES,
  SVC_HYPERTENSION,
  SVC_PSY,
  SVC_KBM,
  SVC_METHADONE,
  SVC_BLOOD_TAKING,
  SVC_WOUND_CARE,
  SVC_FUNDOSCOPY,
  SVC_XRAY,
  SVC_DIET_COUNSELLING,
  SVC_PREMARITAL_SCREENING,
  SVC_MEDICAL_CHECKUP,
  SVC_ANTENATAL_BOOKING,
  SVC_ANTENATAL_FUP,
  SVC_POSTNATAL,
  SVC_FAMILY_PLANNING,
  SVC_PAP_SMEAR,
  SVC_IMMUNIZATION,
  SVC_OTHER_PROBS
]

module.exports = {
  SVC_ALL,
  SVC_FEVER,
  SVC_URTI,
  SVC_ASTHMA,
  SVC_TUBERCULOSIS,
  SVC_ABD_DISCOMFORT,
  SVC_AGE,
  SVC_DIABETES,
  SVC_HYPERTENSION,
  SVC_PSY,
  SVC_KBM,
  SVC_METHADONE,
  SVC_BLOOD_TAKING,
  SVC_WOUND_CARE,
  SVC_FUNDOSCOPY,
  SVC_XRAY,
  SVC_DIET_COUNSELLING,
  SVC_PREMARITAL_SCREENING,
  SVC_MEDICAL_CHECKUP,
  SVC_ANTENATAL_BOOKING,
  SVC_ANTENATAL_FUP,
  SVC_POSTNATAL,
  SVC_FAMILY_PLANNING,
  SVC_PAP_SMEAR,
  SVC_IMMUNIZATION,
  SVC_OTHER_PROBS
}

</script>
